# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Default'

variables:
   - group: sigmoidapp

steps:
- script: | 
      az login -u ${UserName} -p ${Password} 
      az group create --name sigmoidrg --location eastus
  displayName: 'logging into azure portal'

- script: |
      az acr create --name sachinregistry --resource-group sigmoidrg --sku Standard
      az acr login --name sachinregistry 
      docker build . -f Dockerfile -t sachinregistry.azurecr.io/sigmoidapp:latest && sleep 10
      docker push sachinregistry.azurecr.io/sigmoidapp:latest
      #docker pull mcr.microsoft.com/hello-world
      #docker tag mcr.microsoft.com/hello-world sachinregistry.azurecr.io/hello-world:latest
      #docker push sachinregistry.azurecr.io/hello-world:latest
  displayName: 'build and push to ACR'
- script: |
      #az aks create -g sigmoidrg -n sachinscluster --enable-managed-identity --node-count 1 --enable-addons monitoring --generate-ssh-keys
      #az aks get-credentials --resource-group sigmoidrg -n sachinscluster
      kubectl apply -f kube/
      kubectl get deployments
      kubectl get services
  displayName: 'deploy to aks cluster'
