# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Default'

variables:
   - group: sigmoidapp

steps:
- script: | 
      az login -u ${UserName} -p ${Password} 
      az group create --name sigmoidrg --location eastus
  displayName: 'logging into azure portal'

- script: |
      az acr create --name sachinregistry --resource-group sigmoidrg --sku Standard
      az acr login --name sachinregistry 
      #docker build . -f Dockerfile -t sachinregistry.azurecr.io/sigmoidapp:latest && sleep 10
      #docker push sachinregistry.azurecr.io/sigmoidapp:latest
      docker pull sachinhadadi/nginx:v2
      docker tag  sachinhadadi/nginx:v2 sachinregistry.azurecr.io/nginx:latest
      docker push sachinregistry.azurecr.io/nginx:latest
  displayName: 'build and push to ACR'
- script: |
      az aks create -g sigmoidrg -n sachinscluster --node-count 1 --generate-ssh-keys --attach-acr sachinregistry
      az aks get-credentials --resource-group sigmoidrg -n sachinscluster
      kubectl apply -f kube/
      kubectl get deployments
      kubectl get services
  displayName: 'deploying to aks cluster'
