# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Default'

variables:
   - group: sigmoidapp

steps:
- script: | 
      az login -u ${UserName} -p ${Password} 
      az group create --name sigmoidrg --location eastus
  displayName: 'logging into azure portal'

- script: |
      az acr create --resource-group sigmoidrg --name ${RegisterName} --sku Basic
      az acr login --name ${RegisterName}
  displayName: 'build and push to ACR'
