# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Default'

variables:
   - group: sachin

steps:
- script: | 
      az login -u ${UserName} -p ${Password} 
      az group list
  displayName: 'logging into azure portal'

- script: 
  displayName: 'Run a multi-line script'
