apiVersion: v1
kind: Service
metadata:
  name: sigmoid-service
  labels:
    app: sig-app
spec:
   type: LoadBalancer
   selector:
     app: sig-app
   ports:
     - port: 8000
       targetPort: 8000
